### ISSUE TITLE
DTNME Support Update

### ISSUE THREAD

**Issue by joshua-deaton** [ipnsig-pwg/ipnsig-pwg.github.io#1]
DTNME supports all BPv6 and BPv7 features except for BPSec. DTNME also supports BIBE both with custody and independently from Custody as a BP version compatibility mechanism allowing BPv6 bundles to be encapsulated in BPv7 bundles and BPv7 bundles to be encapsulated in BPv6 bundles. No CGR, No SPP, No BSS, No AMS, No IPv6, No IPND, and Yes CFDP. Discovery was removed from DTNME in the clean up for modernization as the mechanism was a bit buggy, We do still support IPN Announcement for each convergence layer, but that doesn't necessarily have to be tracked.

**Comment by marcblanchet** [comment]
we are talking about this repo correct? https://github.com/nasa/DTNME.  Because the repo did not seem to have any commit since 3 years and RFC9171 (BPv7) was published in Jan 2022. Moreover, various grep in the source code does not seem to give any indication of BP7 support, nor the documentation. Same for CFDP.

**Comment by joshua-deaton** [comment]
Yes, so due to the oddity of how DTNME get developed in relation to ISS Flight operations, when things get developed and are ready for public use we release them as Beta branches the latest of which is https://github.com/nasa/dtnme/tree/v1.2.0_Beta the Master branch includes only ISS IVV'd software which most users do not need. I will say I have received authority to release the IVV'd 1.3.1 version as the Master branch so that should be going up shortly either way.

**Comment by marcblanchet** [comment]
got it. Supports RTP over BP?

**Comment by joshua-deaton** [comment]
RTPoverDTN support is in the 1.3.1 release that should be going out in the next day or so.

**Comment by marcblanchet** [comment]
ok. I've put the new version out based on your comments. I haven't put RTP support yet. Please review that the new table is ok.
